// Generated by CoffeeScript 1.3.3
(function() {
  var config, http, options, xml2js;

  http = require('http');

  xml2js = require('xml2js');

  config = require('./config/config');

  options = 'http://testing.shippingapis.com/ShippingAPITest.dll?API=TrackV2&XML=<TrackRequest USERID="' + config.usps.userId + '"><TrackID ID="EJ958083578US"></TrackID></TrackRequest>';

  http.get(options, function(res) {
    res.on('data', function(chunk) {
      var parser;
      parser = new xml2js.Parser();
      return parser.parseString(chunk, function(err, result) {
        return console.log(result.TrackResponse.TrackInfo);
      });
    });
    res.on('end', function() {
      return console.log('done');
    });
    return res.on('error', function(e) {
      return console.log('problems: ' + e.message);
    });
  });

}).call(this);
